### ISSUE TITLE
Separate Mesh By Loose Parts

### ISSUE THREAD

**Issue by alexderpyfox** [Xlinka/NeosPlus#72]
Currently there is only split in pieces by materials but having it be able to be split in all the seperate pieces and join them again in groups or something like the in blender option would be nice i thought of this idea when j saw that a skinned mesh with the cloth physics becomes all the seperate pieces when you collide it with cloth collider

**Comment by DoubleStyx** [comment]
There's a button on mesh assets that lets you separate objects by submesh, but not by loose parts. This feature has been requested before by members of the Neos community. It is possible to do this with a separate component/wizard but not by adding an extra button to the mesh asset/renderer (since that would require patching).

**Comment by alexderpyfox** [comment]
Yes add that without patching

**Comment by Xlinka** [comment]
Closing issue as this is more of a mod issue unless we make a seperate split mesh tooltip.
